export const envs = {
    PRODUCTION: true,
    FT_URL_LOGIN: import.meta.env.FT_URL_LOGIN,
    FT_URL_REGISTER: import.meta.env.FT_URL_REGISTER,
    FT_URL_CLIENT_UPLOAD: import.meta.env.FT_URL_CLIENT_UPLOAD,
    FT_URL_FINANCIER_PROVIDER: import.meta.env.FT_URL_FINANCIER_PROVIDER,
    FT_URL_NEGOTIATION: import.meta.env.FT_URL_NEGOTIATION,
    FT_URN: import.meta.env.FT_URN,

    FT_AUTH_LOGIN: import.meta.env.FT_AUTH_LOGIN,
    FT_AUTH_REGISTER: import.meta.env.FT_AUTH_REGISTER,
    FT_AUTH_CONFIG_USER: import.meta.env.FT_AUTH_CONFIG_USER,
    FT_AUTH_CHANGE_PASSWORD: import.meta.env.FT_AUTH_CHANGE_PASSWORD,
    FT_AUTH_FORGOT_PASSWORD: import.meta.env.FT_AUTH_FORGOT_PASSWORD,

    FT_REGISTER_VERIFY_TOKEN: import.meta.env.FT_REGISTER_VERIFY_TOKEN,
    FT_REGISTER_LIST_DOCUMENT: import.meta.env.FT_REGISTER_LIST_DOCUMENT,
    FT_REGISTER_RENEW_UPDATE_FILES_TOKEN: import.meta.env.FT_REGISTER_RENEW_UPDATE_FILES_TOKEN,
    FT_REGISTER_UPDATE_FAILED_LEGAL_DOCUMENT: import.meta.env.FT_REGISTER_UPDATE_FAILED_LEGAL_DOCUMENT,

    FT_CLIENT_UPLOAD_DATA: import.meta.env.FT_CLIENT_UPLOAD_DATA,
};
